// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GanttChar: typeof import('./src/components/gantt/GanttChar.vue')['default']
    GanttChart: typeof import('./src/components/gantt/GanttChart.vue')['default']
    GanttTable: typeof import('./src/components/gantt/GanttTable.vue')['default']
    GanttView: typeof import('./src/components/gantt/GanttView.vue')['default']
    TableView: typeof import('./src/components/table/TableView.vue')['default']
  }
}

export {}
